= Package Features

:Y: Yes
:N: No

The list of editing features natively supported by the package.


== Associated File Extensions

The following file extensions are automatically recognized as AsciiDoc files:

* `.adoc`
* `.asc`
* `.asciidoc`


== Color Schemes

The package ships with a dedicated color scheme (AsciiDoc Dark) which is enable by default in `Asciidoctor.sublime-settings`:

[source,json]
-------------------------------------------------------
{
  "color_scheme": "AsciiDoc Dark.sublime-color-scheme",
-------------------------------------------------------

You can always override this setting and enforce a color scheme of your choice by creating your own `Asciidoctor.sublime-settings` in the `Packages/User` directory.

The reason I'm currently enforcing the package default scheme is because the package is still under development, and this color scheme reflects the overall direction of my efforts in term of what I believe should be visually highlighted while working with the AsciiDoc syntax.
Therefore, I would like all collaborators to the project to appreciate the native package scheme and its "`flavor,`" so to speak.

Many elements of the AsciiDoc syntax rely on scopes names which are peculiar to AsciiDoc, and very unlikely to be covered by general purpose color schemes designed for programming languages or lightweight markup syntaxes (like Markdown, reST, etc.).


== Snippets

The following table lists the package snippets and their features.

// Attributes definitions for substitutions in Table below:
include::_inc-attributes-snippets-links.adoc[]


[.center]
[%autowidth]
[cols="2*<d,2*^d,<d"]
|=============================================================================
| Name                    | Trigger                           |  S  | W  | Fields

| {snip_Button}           | `btn` kbd:[Tab]                   | {N} |    |
| {snip_CommentBlock}     | `//` kbd:[Tab]                    | {Y} | 78 |
| Document Title          | `h0` kbd:[Tab]                    | {N} |    |
| {snip_ExampleBlock}     | _n/a_                             | {Y} | 78 | Title
| {snip_Footnote}         | `fn` kbd:[Tab]                    | {Y} |    |
| {snip_FootnoteRef}      | `fnr` kbd:[Tab]                   | {Y} |    | ID
| {snip_ImageBlock}       | `img` kbd:[Tab]                   | {N} |    | Title, path, alt text, width, height
| {snip_KbdShortcut}      | `kbd` kbd:[Tab]                   | {N} |    |
| {snip_ListingBlock}     | `--` kbd:[Tab]                    | {Y} | 78 | Lang
| {snip_PassthroughBlock} | _n/a_                             | {Y} | 78 | Title
| {snip_QuotedBlock}      | `__` kbd:[Tab] or `""` kbd:[Tab]  | {Y} | 78 | Attribution, Title
| Section Titles 1–5      | `h1` kbd:[Tab] ... `h5` kbd:[Tab] | {N} |    |
| {snip_SidebarBlock}     | `sbar` kbd:[Tab]                  | {Y} | 78 |
| {snip_Table}            | `{vbar}=` kbd:[Tab]               | {N} | 78 | Caption, cols, opts
|=============================================================================

The meaning of the table columns are:

[horizontal]
[.red]#Name# ::
The exact name of the snippet, for invoking it via the Command Palette.

[.red]#Trigger# ::
The snippet text trigger (if any).

[.red]#S#{nbsp}[_Selection_] ::
whether the snippets preserve or not the current selection (if any).

[.red]#W#{nbsp}[_Width_] ::
The width of elements which can be optionally represented my multiple characters, e.g. block delimiters.
In most cases, block delimiters generated via snippets are extended to 78 characters, for decorative purposes.

[.red]#Fields# ::
The list of extra supported fields (if any) which the user can navigate through via kbd:[Tab], usually holding some preset values.


== Completions

* Provides completions for attributes (built-in and locally defined) and cross references (local anchors and titles).


== Keymap Details


=== Comments

Both inline and block comments are support via the default Sublime Text key bindings -- usually, kbd:[Ctrl]+kbd:[Numpad /] and kbd:[Ctrl]+kbd:[Shift]+kbd:[Numpad /], respectively.


=== Auto-Paired Punctuation

* Asterisks (strong), underscores (emphasis), backticks (monospaced), English quotation marks, and Czech quotation marks are autopaired and will wrap selected text.
** If you start an empty pair and hit backspace, both elements are deleted.
** If you start an empty asterisks pair and hit kbd:[Space] or kbd:[Tab], the right element is deleted (because you probably wanted to start a list, not a strong text).


=== Lists and Callouts

* At the end of a list item (ordered or unordered), pressing kbd:[Enter] will automatically insert the new list item "`bullet.`"
** Pressing kbd:[Enter] on the blank list item will remove it.
** Pressing kbd:[Tab] on the blank list item, or selected item(s), will increase the nesting level and indent it.
** Pressing kbd:[Shift] + kbd:[Tab] on the blank list item, or selected item(s), will decrease nesting level and unindent it.
* At the end of a callouts list item, pressing kbd:[Enter] will automatically insert the new list item with an incremented number.
** Pressing kbd:[Enter] on the blank list item will remove it.

// @TODO: Explain how to disable lists indentation!

TIP: You can disable indentation of list items in your settings file.


== Symbols Indexing

This section illustrates how the package handles {ST_SymbolsIndexing} and the various Goto functionality associated with it:

[horizontal]
Local symbols ::
i.e symbols in the current document -- accessible via:
* _Menu_: menu:Goto[Goto Symbol...]
* _Keyboard_: kbd:[Ctrl]+kbd:[R]/kbd:[Cmd]+kbd:[R]

Global{nbsp}symbols ::
i.e symbols in the current project -- accessible via:
* _Menu_: menu:Goto[Goto Symbol in Project...]
* _Keyboard_: kbd:[Ctrl]+kbd:[Shift]+kbd:[R]/kbd:[Cmd]+kbd:[Shift]+kbd:[R]

=== Section Titles

Document and section titles are displayed in both the local and global _Goto Symbol_ lists:

* In the local symbol list, titles are nicely indented according to hierarchy.
* In the global symbol list, titles are prefixed with `=` characters (as in the AsciiDoc source), which allows to quickly filter them out by typing `=`, as well as providing an easy visual cue to identify them.

////
// This is no longer true with ST4:
Furthermore, they will be on top of the list because of the precedence of `=`.
////


== Build System

This package defines a build system for AsciiDoc files that targets *HTML*, *EPUB*, and *DOCX*.
With the source AsciiDoc file open in the editor, simply press kbd:[Ctrl]+kbd:[Shift]+kbd:[B] to invoke the build system, and then select your target.

.Targets
[opts="autowidth"]
|=============================================================================
| Asciidoctor        | Generates HTML
| Asciidoctor - EPUB | Generates EPUB (via `asciidoctor-epub3`)
| Asciidoctor - DOCX | Generates a Word document (via `pandoc`)
|=============================================================================

Or, press kbd:[Ctrl]+kbd:[B] to repeat the build for the last target selected.

In all cases, the generated file will be placed alongside the source file, in the same folder.
In the case of a DOCX file, it will be opened automatically using your system's default program for the DOCX file type.

=== Build System Requirements

* For HTML, this assumes that `asciidoctor` is installed on the system path.
* For EPUB, this assumes that `asciidoctor-epub3` is installed on the system path.
* For DOCX, this assumes that `pandoc` is installed on the system path (along with `asciidoctor`).

NOTE: There is currently only a `Windows` implementation for DOCX.

=== Specifying a reference.docx file for Pandoc

Pandoc has the ability to start with a reference DOCX file that, for example, defines all of the paragraph and character styles you'd like to be included in the target.
This build system supports three different ways to specify such a reference docx file for pandoc to use:

. If the AsciiDoc source file contains an attribute definition for `:pandoc:`, `:pandoc-ref:`, or `:pandoc-reference:`, and the value of that attribute exists as a file, then it will be used.
NOTE: There is nothing special about us using an attribute definition for this.
This build system searches the source file directly for the file reference, so we could have buried it in a comment, for example.
Using attribute syntax just seemed appropriate.
By the time the source file is processed by AsciiDoctor, the `:pandoc...:` attribute will just be ignored.
Be aware that if there are multiple `:pandoc...:` attributes defined in the file, only the last one will be used.
Also, this script will only find `:pandoc...:` attributes that are in the main source file, not in any included files.

. If `.\reference.docx` exists, it will be used.

. If `.\.pandoc\reference.docx` exists, it will be used.

. Otherwise, no reference file will be used.

=== Usage Tips

You can leave an *HMTL* file open in your browser while you regenerate it.
Then, just refresh the page with kbd:[F5].
For *EPUB* and *DOCX* files, however, you must close them before they can be regenerated.
