= Keymap Details

== Auto-Paired Punctuation

* Asterisks (strong), underscores (emphasis), backticks (monospaced), English quotation marks, and Czech quotation marks are autopaired and will wrap selected text.
** If you start an empty pair and hit backspace, both elements are deleted.
** If you start an empty asterisks pair and hit `Space` or `Tab`, the right element is deleted (because you probably wanted to start a list, not a strong text).

== Lists and Callouts

* At the end of a list item (ordered or unordered), pressing `Enter` will automatically insert the new list item "bullet."
** Pressing `Enter` on the blank list item will remove it.
** Pressing `Tab` on the blank list item, or selected item(s), will increase the nesting level and indent it.
** Pressing `Shift` + `Tab` on the blank list item, or selected item(s), will decrease nesting level and unindent it.
** Note: You can disable indentation of list items in your settings file.
* At the end of a callouts list item, pressing `Enter` will automatically insert the new list item with an incremented number.
** Pressing `Enter` on the blank list item will remove it.
